// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab_63_ToDo_API_Users_Categories.Models;

namespace lab_63_ToDo_API_Users_Categories.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    [Migration("20200306105744_adding-seed-data")]
    partial class addingseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab_63_ToDo_API_Users_Categories.Models.ToDo", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ToDoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ToDoId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            ToDoId = 1,
                            ToDoName = "Do This"
                        },
                        new
                        {
                            ToDoId = 2,
                            ToDoName = "And Do This"
                        },
                        new
                        {
                            ToDoId = 3,
                            ToDoName = "And Do This Also"
                        });
                });

            modelBuilder.Entity("lab_63_ToDo_API_Users_Categories.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserName = "Fred"
                        },
                        new
                        {
                            UserId = 2,
                            UserName = "Bob"
                        },
                        new
                        {
                            UserId = 3,
                            UserName = "Pete"
                        },
                        new
                        {
                            UserId = 4,
                            UserName = "Tim"
                        },
                        new
                        {
                            UserId = 5,
                            UserName = "Serena"
                        });
                });

            modelBuilder.Entity("lab_63_ToDo_API_Users_Categories.Models.ToDo", b =>
                {
                    b.HasOne("lab_63_ToDo_API_Users_Categories.Models.User", "User")
                        .WithMany("ToDos")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
